export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';
export const ORDER_UPDATE_RESET = 'ORDER_UPDATE_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_MINE_LIST_REQUEST = 'ORDER_MINE_LIST_REQUEST';
export const ORDER_MINE_LIST_SUCCESS = 'ORDER_MINE_LIST_SUCCESS';
export const ORDER_MINE_LIST_FAIL = 'ORDER_MINE_LIST_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const ORDER_BAYAR_REQUEST = 'ORDER_BAYAR_REQUEST';
export const ORDER_BAYAR_SUCCESS = 'ORDER_BAYAR_SUCCESS';
export const ORDER_BAYAR_FAIL = 'ORDER_BAYAR_FAIL';
export const ORDER_BAYAR_RESET = 'ORDER_BAYAR_RESET';

export const ORDER_CITY_REQUEST = 'ORDER_CITY_REQUEST';
export const ORDER_CITY_SUCCESS = 'ORDER_CITY_SUCCESS';
export const ORDER_CITY_FAIL = 'ORDER_CITY_FAIL';
export const ORDER_CITY_RESET = 'ORDER_CITY_RESET';

export const ORDER_PROVINCE_REQUEST = 'ORDER_PROVINCE_REQUEST';
export const ORDER_PROVINCE_SUCCESS = 'ORDER_PROVINCE_SUCCESS';
export const ORDER_PROVINCE_FAIL = 'ORDER_PROVINCE_FAIL';
export const ORDER_PROVINCE_RESET = 'ORDER_PROVINCE_RESET';

export const ORDER_ONGKIR_REQUEST = 'ORDER_ONGKIR_REQUEST';
export const ORDER_ONGKIR_SUCCESS = 'ORDER_ONGKIR_SUCCESS';
export const ORDER_ONGKIR_FAIL = 'ORDER_ONGKIR_FAIL';
export const ORDER_ONGKIR_RESET = 'ORDER_ONGKIR_RESET';

export const ORDER_ONGKIR_POS_REQUEST = 'ORDER_ONGKIR_POS_REQUEST';
export const ORDER_ONGKIR_POS_SUCCESS = 'ORDER_ONGKIR_POS_SUCCESS';
export const ORDER_ONGKIR_POS_FAIL = 'ORDER_ONGKIR_POS_FAIL';
export const ORDER_ONGKIR_POS_RESET = 'ORDER_ONGKIR_POS_RESET';

export const ORDER_ONGKIR_TIKI_REQUEST = 'ORDER_ONGKIR_TIKI_REQUEST';
export const ORDER_ONGKIR_TIKI_SUCCESS = 'ORDER_ONGKIR_TIKI_SUCCESS';
export const ORDER_ONGKIR_TIKI_FAIL = 'ORDER_ONGKIR_TIKI_FAIL';
export const ORDER_ONGKIR_TIKI_RESET = 'ORDER_ONGKIR_TIKI_RESET';